--- a/.github/workflows/sync-default-branches.yml
+++ b/.github/workflows/sync-default-branches.yml
@@ -61,4 +61,4 @@
         run: git push origin "${TARGET_SHA}:refs/heads/${TARGET_BRANCH}" --force
         env:
           TARGET_SHA: ${{ steps.sha.outputs.target }}
-          TARGET_BRANCH: ${{ steps.branches.outputs.target }}
+          TARGET_BRANCH: ${{ steps.branches.outputs.target }}